name: CI/CD Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check black formatting
      run: |
          black --check src/ tests/

    - name: Verify critical imports
      run: |
        python -c "import tensorflow as tf; print('Imports OK')"
        python -c "from huggingface_hub import hf_hub_download; print('HF Hub OK')"


  approve-pr:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title
        run: |
          if [[ ! "${{ github.event.pull_request.title }}" =~ ^(feat|fix|docs|refactor|test|chore): ]]; then
            echo "::error::PR title must follow semantic format (e.g., 'feat: add UNet')"
            exit 1
          fi

      - name: Label approved PRs
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['approved-for-merge']
            })
