name: SkinSight Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify critical imports
      run: |
        python -c "import tensorflow as tf; print('Imports OK')"
        python -c "from huggingface_hub import hf_hub_download; print('HF Hub OK')"
